-- AlterTable
ALTER TABLE `jobs` MODIFY `type` ENUM('VTU_TRANSACTION', 'WHATSAPP_MESSAGE', 'USSD_SESSION', 'SUBSCRIPTION_PROCESSING', 'PRE_ORDER_PROCESSING', 'LOAN_PROCESSING', 'NOTIFICATION', 'SCHEDULED_JOB', 'TARIFF_CHECK', 'VENDOR_HEALTH_CHECK', 'TOKEN_EXPIRY_CHECK', 'LOAN_REMINDER', 'LOAN_DELINQUENCY_CHECK', 'USSD_CLEANUP', 'API_REQUEST', 'WEBHOOK_DELIVERY', 'BULK_OPERATION', 'QR_PAYMENT', 'OTP_DELIVERY', 'WALLET_FUNDING', 'WHATSAPP_REMINDER') NOT NULL;

-- AlterTable
ALTER TABLE `users` ADD COLUMN `lastWhatsAppReminder` DATETIME(3) NULL;
