-- AlterTable
ALTER TABLE `vendors` MODIFY `type` ENUM('VTPASS', 'QUICKTELLER', 'MONIEPOINT', 'FLUTTERWAVE_VTU', 'BILAL_SADA', 'LEGITDATAWAY') NOT NULL;

-- AlterTable
ALTER TABLE `vtu_transactions` MODIFY `vendor` ENUM('VTPASS', 'QUICKTELLER', 'MONIEPOINT', 'FLUTTERWAVE_VTU', 'BILAL_SADA', 'LEGITDATAWAY') NULL;
